[package]
name = "em-libs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0"
rand = "0.8"
sha2 = "0.10"
uuid = { version = "1.4", features = ["serde", "v4"] }